version: '3'
services:
  server:
    build: .
    links:
     - db
    environment:
     - NODE_CONFIG: >
        {"DATABASE_URL":"http://db:5984"}

  client:
    build:
      dockerfile: Dockerfile.client
      context: .

  db:
    build:
      dockerfile: Dockerfile.db
      context: .
    volumes:
     - ./db:/app/db
