FROM mhart/alpine-node:8

RUN mkdir /app

WORKDIR /app

RUN npm install -g pouchdb-server

COPY db/config.json /app/db/

EXPOSE 5984

VOLUME /app/db

CMD ["./node_modules/.bin/pouchdb-server", "-c", "db/config.json"]

